name: agriplant
description: Agriculture plant app
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  intl: ^0.19.0
  google_fonts: ^6.2.1
  badges: ^3.1.1
  timelines: ^0.1.0
  easy_stepper: ^0.8.5+1
  awesome_dialog: ^3.2.1
  shared_preferences: ^2.5.3
  rxdart: ^0.28.0
  auto_size_text: ^3.0.0

  # Firebase packages
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  firebase_storage: ^12.3.7
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  sign_in_button: ^3.2.0
  google_sign_in: ^6.2.2
  provider: ^6.1.2

  flutter_localizations:
    sdk: flutter

  app_settings: ^6.1.1
  record: ^6.0.0
  audioplayers: ^6.4.0
  image_picker: ^1.1.2
  file_picker: ^10.0.0
  firebase_app_check: ^0.3.2+5
  smooth_page_indicator: ^1.2.1
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  dropdown_button2: ^2.3.9
  flutter_local_notifications: ^19.1.0
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"
  intl_utils: ^2.0.0

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
  class_name: S
  main_locale: ar
  localizations:
    - en
    - ar
    - fr

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/ilogo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"
  adaptive_icon_monochrome: "assets/logo.png"
  icon_size: 100
  web:
    generate: true
    image_path: "assets/ilogo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/ilogo.png"
    icon_size: 100
  macos:
    generate: true
    image_path: "assets/ilogo.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/services/
    - assets/become/
    - shorebird.yaml
