
name: agriplant
description: Agriculture plant app
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  google_fonts: ^5.1.0
  badges: ^3.1.1
  timelines: ^0.1.0
  easy_stepper: ^0.7.3
  awesome_dialog: ^3.2.1
  shared_preferences: ^2.5.2
  rxdart: ^0.27.7

#firebase packages
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  firebase_storage: ^12.3.7
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  sign_in_button: ^3.2.0
  google_sign_in: ^6.2.2
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  app_settings: ^5.2.0
  record: ^6.0.0
  audioplayers: ^6.4.0
  image_picker: ^1.1.2
  file_picker: ^10.0.0
  firebase_app_check: ^0.3.2+5
  smooth_page_indicator: ^1.2.1
  timeago: ^3.7.0
  
  


# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.



# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/ilogo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#AAFFBF00"
  adaptive_icon_foreground: "assets/logo.png" 
  icon_size: 100
  web:
    generate: true
    image_path: "assets/ilogo.png"  
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/ilogo.png"  
    icon_size: 100 
  macos:
    generate: true
    image_path: "assets/ilogo.png"  

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/services/
    - assets/become/
    - shorebird.yaml
