// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Ky8Xd0lU-H_pov1RZgsPcZJuLddo7UI',
    appId: '1:481243125761:web:860b77b938079b74324800',
    messagingSenderId: '481243125761',
    projectId: 'agri-plantt',
    authDomain: 'agri-plantt.firebaseapp.com',
    storageBucket: 'agri-plantt.firebasestorage.app',
    measurementId: 'G-143E26YS9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp0y4hjjMRnarQSDl1WiUAD-HBabSTjbU',
    appId: '1:481243125761:android:b671e4f5fdc177e1324800',
    messagingSenderId: '481243125761',
    projectId: 'agri-plantt',
    storageBucket: 'agri-plantt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqQ2ha0YiiI8Clz1Uxhdd9BuuVp0p7KVM',
    appId: '1:481243125761:ios:642c21467d013458324800',
    messagingSenderId: '481243125761',
    projectId: 'agri-plantt',
    storageBucket: 'agri-plantt.firebasestorage.app',
    iosBundleId: 'com.example.agricplant.agriplant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqQ2ha0YiiI8Clz1Uxhdd9BuuVp0p7KVM',
    appId: '1:481243125761:ios:642c21467d013458324800',
    messagingSenderId: '481243125761',
    projectId: 'agri-plantt',
    storageBucket: 'agri-plantt.firebasestorage.app',
    iosBundleId: 'com.example.agricplant.agriplant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4Ky8Xd0lU-H_pov1RZgsPcZJuLddo7UI',
    appId: '1:481243125761:web:f08fd0fb59f109b1324800',
    messagingSenderId: '481243125761',
    projectId: 'agri-plantt',
    authDomain: 'agri-plantt.firebaseapp.com',
    storageBucket: 'agri-plantt.firebasestorage.app',
    measurementId: 'G-KTWKDDZFJC',
  );
}
